[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = ['pip install -r KeyFinder-Server/requirements.txt']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'python main.py'
