import { StyleSheet } from 'react-native';

// COMPLETE STYLES OBJECT
export const styles = StyleSheet.create({
  // Main app styles
   container: {
    flex: 1,
    backgroundColor: '#121212',
    alignItems: 'center',
  },
  header: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 30,
    height: 80,
    marginTop: 10,
  },
  headerLeft: {
    width: 40,
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  headerRight: {
    width: 40,
  },
  logoImage: {
    width: 300,
    height: 80,
    resizeMode: 'contain',
  },
  subtitle: {
    fontSize: 16,
    color: '#B3B3B3',
    marginTop: -10,
    textAlign: 'center',
  },
  mainContent: {
    flex: 1,
    width: '90%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuButton: {
    backgroundColor: '#282828',
    borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 25,
    width: '100%',
    marginBottom: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuIcon: {
    marginRight: 15,
  },
  menuButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  featureScreen: {
    flex: 1,
    width: '90%',
    alignItems: 'center',
    paddingTop: 20,
  },
  featureScreenContainer: {
    flex: 1,
    width: '90%',
  },
  featureScreenContent: {
    alignItems: 'center',
    paddingTop: 20,
  },
  featureTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 20,
  },
  artistSuggestionCard: {
    backgroundColor: '#282828',
    borderRadius: 8,
    padding: 15,
    marginBottom: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#8420d0',
  },
  artistSuggestionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  artistSuggestionName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    flex: 1,
  },
  artistBadges: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  keyRankBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 8,
  },
  keyRankText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: 'bold',
  },
  bpmMatchBadge: {
    backgroundColor: '#FF6B35',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 6,
  },
  bpmMatchText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: 'bold',
  },
  artistSuggestionDetails: {
    fontSize: 14,
    color: '#B3B3B3',
    marginBottom: 10,
  },
  songsInKeyContainer: {
    backgroundColor: '#1C1C1C',
    borderRadius: 6,
    padding: 10,
    marginTop: 8,
  },
  songsInKeyTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#8420d0',
    marginBottom: 6,
  },
  songInKeyText: {
    fontSize: 13,
    color: '#CCCCCC',
    marginBottom: 3,
    paddingLeft: 5,
  },
  producerTipCard: {
    flexDirection: 'row',
    backgroundColor: '#1A2F1A',
    borderRadius: 8,
    padding: 12,
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#8420d0',
  },
  producerTipContent: {
    flex: 1,
    marginLeft: 10,
  },
  producerTipTitle: {
    color: '#8420d0',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  producerTipText: {
    color: '#CCCCCC',
    fontSize: 13,
    lineHeight: 18,
  },

  // SearchByKey specific styles
  searchContainer: {
    flex: 1,
    backgroundColor: '#121212',
    width: '100%',
  },
  searchHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 15,
  },
  searchTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  toggleButton: {
    backgroundColor: '#282828',
    padding: 8,
    borderRadius: 20,
  },
  selectionSection: {
    backgroundColor: '#1A1A1A',
    marginHorizontal: 15,
    borderRadius: 12,
    paddingVertical: 10,
    marginBottom: 15,
    zIndex: 10, // Keep this for iOS touch issues
  },
  dropdownSection: {
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  genreSection: {
    paddingHorizontal: 15,
    paddingBottom: 10,
  },
  selectorLabel: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  resultsSection: {
    paddingHorizontal: 20,
    flex: 1,
  },
  resultsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  resultsTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  resultsCount: {
    fontSize: 12,
    color: '#8420d0',
    fontWeight: '600',
  },
  bpmSliderContainer: {
    paddingHorizontal: 15,
    paddingBottom: 15,
  },
  bpmLabelContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  bpmValueText: {
    color: '#B3B3B3',
    fontSize: 14,
    fontWeight: '600',
  },
  filterToggleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingBottom: 10,
  },
  filterToggleLabel: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },

  // --- NEW CUSTOM PICKER STYLES ---
  pickerDisplayButton: {
    backgroundColor: '#282828',
    borderRadius: 6,
    paddingVertical: 12,
    paddingHorizontal: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pickerDisplayText: {
    color: '#FFFFFF',
    fontSize: 14,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.7)',
  },
  modalContent: {
    backgroundColor: '#1A1A1A',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    height: 'auto', 
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#444',
    paddingBottom: 15,
    marginBottom: 10,
  },
  modalTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  modalCloseButtonText: {
    color: '#8420d0',
    fontSize: 16,
    fontWeight: '600',
  },
  modalItem: {
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  modalItemText: {
    color: '#FFFFFF',
    fontSize: 16,
  },
  modalItemSelectedText: {
    color: '#8420d0',
    fontSize: 16,
    fontWeight: 'bold',
  },


  // SearchByArtist specific styles
  searchContainer2: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    marginBottom: 15,
  },
  inputField: {
    backgroundColor: '#282828',
    color: '#FFFFFF',
    flex: 1,
    borderRadius: 8,
    padding: 15,
    fontSize: 16,
    marginRight: 10,
  },
  searchIconButton: {
    backgroundColor: '#282828',
    padding: 15,
    borderRadius: 8,
  },
  popularArtistsContainer: {
    width: '100%',
    marginBottom: 20,
  },
  popularArtistsTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 10,
  },
  popularArtistsScroll: {
    flexDirection: 'row',
  },
  popularArtistButton: {
    backgroundColor: '#8420d0',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    marginRight: 8,
  },
  popularArtistText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  analysisSection: {
    width: '100%',
    backgroundColor: '#282828',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
  },
  analysisSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  keyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  keyBadge: {
    backgroundColor: '#8420d0',
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    width: '48%',
    alignItems: 'center',
  },
  keyBadgeText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  keyBadgeRank: {
    color: '#FFFFFF',
    fontSize: 12,
    marginTop: 2,
  },
  bpmContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 10,
  },
  bpmStat: {
    alignItems: 'center',
  },
  bpmStatLabel: {
    color: '#B3B3B3',
    fontSize: 14,
    marginBottom: 4,
  },
  bpmStatValue: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
  },
  bpmRecommendation: {
    color: '#8420d0',
    fontSize: 14,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  artistSongCard: {
    backgroundColor: '#1C1C1C',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  artistSongHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  artistSongTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    flex: 1,
  },
  artistSongPopularity: {
    color: '#8420d0',
    fontSize: 12,
    fontWeight: 'bold',
  },
  artistSongDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  artistSongKey: {
    color: '#8420d0',
    fontSize: 14,
  },
  artistSongBpm: {
    color: '#B3B3B3',
    fontSize: 14,
  },
  artistSongRelease: {
    color: '#B3B3B3',
    fontSize: 12,
    fontStyle: 'italic',
  },
  songGenres: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 6,
  },
  songGenreTag: {
    backgroundColor: '#8420d0',
    color: '#FFFFFF',
    fontSize: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    marginRight: 6,
    marginBottom: 4,
  },
  genreContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  genreBadge: {
    backgroundColor: '#8420d0',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginHorizontal: 4,
    marginBottom: 8,
  },
  genreBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  analysisResults: {
    width: '100%',
    flex: 1,
  },
  analysisTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 10,
    textAlign: 'center',
  },
  dataSource: {
    fontSize: 12,
    color: '#B3B3B3',
    textAlign: 'center',
    marginBottom: 20,
  },

  // Artist Profile Image styles
  artistProfileContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  artistProfileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 3,
    borderColor: '#8420d0',
  },

  // Song card styles
  songCard: {
    backgroundColor: '#282828',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
  },
  songHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  songTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    flex: 1,
  },
  popularityBadge: {
    backgroundColor: '#8420d0',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  popularityText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  songArtist: {
    fontSize: 14,
    color: '#B3B3B3',
    marginBottom: 8,
  },
  songDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  songBpm: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  songGenre: {
    fontSize: 14,
    color: '#8420d0',
    fontWeight: '500',
  },

  // Enhanced song card styles for database integration
  songCardContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  songCoverContainer: {
    marginRight: 15,
  },
  songCoverArt: {
    width: 60,
    height: 60,
    borderRadius: 8,
  },
  songCoverPlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 8,
    backgroundColor: '#1C1C1C',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#333',
  },
  songInfoContainer: {
    flex: 1,
  },
  rankBadge: {
    backgroundColor: '#8420d0',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 10,
  },
  rankText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 15,
    marginBottom: 4,
  },
  detailText: {
    fontSize: 12,
    color: '#B3B3B3',
    marginLeft: 6,
  },

  // Common styles
  loadingContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    color: '#B3B3B3',
    marginTop: 10,
    fontSize: 14,
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
  },
  errorText: {
    color: '#FF453A',
    fontSize: 14,
    marginLeft: 8,
    textAlign: 'center',
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    color: '#B3B3B3',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 10,
  },
  emptySubtext: {
    color: '#666',
    fontSize: 12,
    marginTop: 5,
  },

  // Detect screen styles
   detectButtonIcon: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
  },
  listenButtonWrapper: {
    width: 280,
    height: 280,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listenButton: {
    width: 220,
    height: 220,
    borderRadius: 110,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
    overflow: 'hidden',
  },
  idleButton: {
    backgroundColor: '#8420d0',
  },
  recordingButton: {
    backgroundColor: '#FF453A',
  },
  ripple: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(255, 69, 58, 0.5)',
  },
  statusLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#B3B3B3',
    marginBottom: 20,
    textAlign: 'center',
  },
  resultsPage: {
    flex: 1,
    width: '100%',
  },
  resultsScrollView: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 20,
  },
  analysisContainer: {
    width: '100%',
    alignItems: 'center',
    paddingBottom: 20,
  },
  mainKeyContainer: {
    width: '100%',
    backgroundColor: '#282828',
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    marginBottom: 10,
  },
  mainKeyValue: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#8420d0',
    marginVertical: 5,
  },
  relativeKeyText: {
    fontSize: 16,
    color: '#B3B3B3',
    fontWeight: '600',
    marginTop: 5,
  },
  secondaryResultsContainer: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 10,
  },
  resultBox: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#282828',
    padding: 20,
    borderRadius: 12,
    marginHorizontal: 5,
    flex: 1,
  },
  resultLabel: {
    fontSize: 14,
    color: '#B3B3B3',
    fontWeight: '600',
    marginBottom: 8,
  },
  resultValue: {
    fontSize: 36,
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  alternativeKeyText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '600',
    textAlign: 'center',
  },
  keyboardContainer: {
    width: '100%',
    height: 80,
    flexDirection: 'row',
    position: 'relative',
    marginTop: 15,
  },
  whiteKey: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 4,
    margin: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 5,
  },
  blackKeysContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '60%',
    flexDirection: 'row',
    paddingHorizontal: '7.14%',
  },
  blackKeyWrapper: {
    flex: 1,
    alignItems: 'center',
  },
  blackKey: {
    width: '70%',
    height: '100%',
    backgroundColor: '#000000',
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 4,
    zIndex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 2,
  },
  blackKeyText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 10,
  },
  highlightedKey: {
    backgroundColor: '#8420d0',
  },
  keyText: {
    color: '#000',
    fontWeight: 'bold',
    fontSize: 10,
  },
  detectedSongContainer: {
    width: '100%',
    marginTop: 10,
  },
  suggestionsTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 10,
    paddingLeft: 10,
  },
  suggestionsSubtitle: {
    fontSize: 14,
    color: '#B3B3B3',
    marginBottom: 10,
    paddingLeft: 10,
  },
  suggestionCard: {
    backgroundColor: '#282828',
    borderRadius: 8,
    padding: 15,
    marginBottom: 10,
  },
  recognizedCard: {
    backgroundColor: '#8420d0',
    padding: 10,
  },
  recognizedCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  albumArt: {
    width: 60,
    height: 60,
    borderRadius: 6,
    marginRight: 15,
  },
  albumArtPlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 6,
    marginRight: 15,
    backgroundColor: '#333333',
    justifyContent: 'center',
    alignItems: 'center',
  },
  recognizedSongInfo: {
    flex: 1,
  },
  albumInfo: {
    fontSize: 12,
    color: '#DDDDDD',
    marginTop: 4,
  },
  suggestionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  suggestionArtist: {
    fontSize: 14,
    color: '#B3B3B3',
    marginTop: 4,
  },
  chordProgressionCard: {
    backgroundColor: '#1C1C1C',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    alignItems: 'center',
  },
  chordProgressionText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'monospace',
  },
  waveformContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: '60%',
    width: '100%',
  },
  waveformBar: {
    width: 10,
    backgroundColor: 'white',
    marginHorizontal: 4,
    borderRadius: 5,
    height: '80%',
  },
  detectAnotherButton: {
    backgroundColor: '#8420d0',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 30,
    margin: 20,
    alignItems: 'center',
  },
  detectAnotherButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  confidenceText: {
    fontSize: 16,
    fontWeight: '600',
    marginTop: 4,
    marginBottom: 4,
  },
  // New Session Screen Styles
  inputGroup: {
    width: '100%',
    marginBottom: 20,
  },
  inputLabel: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  artistInfoCard: {
    backgroundColor: '#282828',
    borderRadius: 12,
    padding: 15,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  artistImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    marginRight: 15,
  },
  artistInfoText: {
    flex: 1,
  },
  artistName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  artistSubtext: {
    fontSize: 14,
    color: '#B3B3B3',
    marginTop: 4,
  },
  dropboxButton: {
    backgroundColor: '#F7F7F7',
    borderRadius: 8,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dropboxButtonLinked: {
    backgroundColor: '#0061FF',
    borderRadius: 8,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dropboxButtonText: {
    color: '#0061FF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  dropboxButtonTextLinked: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  primaryButton: {
    backgroundColor: '#8420d0',
    paddingVertical: 15,
    borderRadius: 30,
    width: '100%',
    alignItems: 'center',
    marginTop: 10,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  folderItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#404040',
  },
  folderName: {
    color: '#FFFFFF',
    fontSize: 16,
  },
  closeButton: {
    backgroundColor: '#FF453A',
    borderRadius: 8,
    padding: 15,
    marginTop: 20,
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  redirectUriText: {
      color: '#B3B3B3',
      marginTop: 20,
      fontSize: 14,
      textAlign: 'center',
  },
  redirectUriInput: {
      backgroundColor: '#282828',
      color: '#FFFFFF',
      width: '100%',
      borderRadius: 8,
      padding: 10,
      fontSize: 12,
      marginTop: 10,
      textAlign: 'center',
  },
  folderNavBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingBottom: 10,
      marginBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: '#404040',
  },
  currentPathText: {
      color: '#FFFFFF',
      fontSize: 16,
      flex: 1,
      textAlign: 'center',
      marginHorizontal: 10,
  },
  selectFolderButton: {
      backgroundColor: '#1DB954',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 6,
  },
  selectFolderButtonText: {
      color: '#FFFFFF',
      fontWeight: 'bold',
  },
  statsText: {
    color: '#FFFFFF',
    fontSize: 16,
    marginVertical: 4,
  },
  songStats: {
      marginLeft: 'auto',
      alignItems: 'flex-end',
  },
  selectedFolderDisplay: {
      backgroundColor: '#1C1C1C',
      borderRadius: 8,
      padding: 15,
      marginBottom: 20,
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
  },
  selectedFolderText: {
      color: '#FFFFFF',
      fontSize: 16,
      flex: 1, // Allow text to take up space
      marginRight: 10, // Space from button
  },
  browseButton: {
      backgroundColor: '#8420d0', // Use your accent color
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 20,
  },
  browseButtonText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: 'bold',
  },
  // Pagination styles
  loadMoreButton: {
    backgroundColor: '#8420d0',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginVertical: 20,
    alignItems: 'center',
    alignSelf: 'center',
  },
  loadMoreText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  resultsSummary: {
    paddingVertical: 15,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#404040',
    marginTop: 10,
  },
  resultsSummaryText: {
    color: '#B3B3B3',
    fontSize: 14,
    fontStyle: 'italic',
  },
  // Database insights styles
  databaseInsightsCard: {
    backgroundColor: '#1C1C1C',
    borderRadius: 8,
    padding: 15,
    marginBottom: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#1DB954',
  },
  databaseInsightsText: {
    color: '#FFFFFF',
    fontSize: 14,
    marginBottom: 5,
    lineHeight: 20,
  },
});

// Session styles - separate export for debugging
export const sessionStyles = StyleSheet.create({
  sessionCard: {
    backgroundColor: '#282828',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  sessionCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  sessionArtistImageContainer: {
    marginRight: 12,
  },
  sessionArtistImage: {
    width: 40,
    height: 40,
    borderRadius: 6,
  },
  sessionArtistImagePlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 6,
    backgroundColor: '#2A2A2A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sessionCardDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  sessionCardType: {
    color: '#8420d0',
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 8,
  },
  sessionCardNotes: {
    color: '#999',
    fontSize: 12,
    marginTop: 4,
    fontStyle: 'italic',
  },
  sessionCardTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  sessionCardDate: {
    color: '#999',
    fontSize: 12,
    marginTop: 2,
  },
  sessionCardInfo: {
    flex: 1,
  },
});

// Compact picker styles
export const compactPickerStyles = StyleSheet.create({
  inputIOS: {
    fontSize: 14,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#404040',
    borderRadius: 6,
    color: '#FFFFFF',
    backgroundColor: '#282828',
    paddingRight: 25,
  },
  inputAndroid: {
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#404040',
    borderRadius: 6,
    color: '#FFFFFF',
    backgroundColor: '#282828',
    paddingRight: 25,
  },

  // Enhanced Session Styles
  searchErrorContainer: {
    marginBottom: 16,
  },
  errorMessageCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2A2A2A',
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#FFA500',
    marginBottom: 8,
  },
  errorMessageText: {
    color: '#FFFFFF',
    fontSize: 14,
    marginLeft: 8,
    flex: 1,
  },
  createCustomButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2A2A2A',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8420d0',
  },
  createCustomButtonText: {
    color: '#8420d0',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
  },
  sessionCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  sessionArtistImageContainer: {
    marginRight: 12,
  },
  sessionArtistImage: {
    width: 40,
    height: 40,
    borderRadius: 6,
  },
  sessionArtistImagePlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 6,
    backgroundColor: '#2A2A2A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sessionCardDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  sessionCardType: {
    color: '#8420d0',
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 8,
  },
  sessionCardNotes: {
    color: '#999',
    fontSize: 12,
    marginTop: 4,
    fontStyle: 'italic',
  },

  // Artist Search Suggestions Styles
  searchSuggestionsContainer: {
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#404040',
  },
  suggestionsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  suggestionsHeaderText: {
    color: '#8420d0',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1A1A1A',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  suggestionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  suggestionImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  suggestionImagePlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#333',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  suggestionInfo: {
    flex: 1,
  },
  suggestionName: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  suggestionDetails: {
    color: '#999',
    fontSize: 12,
    marginTop: 2,
  },
  suggestionsDivider: {
    height: 1,
    backgroundColor: '#404040',
    marginVertical: 8,
  },
  createCustomSuggestionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    padding: 8,
  },
  createCustomSuggestionText: {
    color: '#666',
    fontSize: 14,
    marginLeft: 8,
    fontStyle: 'italic',
  },
  artistImagePlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 8,
    backgroundColor: '#2A2A2A',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },

  // Missing Session Screen Text Styles
  featureTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 20,
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    marginTop: 16,
    textAlign: 'center',
  },
  emptySubtext: {
    fontSize: 14,
    color: '#999',
    marginTop: 8,
    textAlign: 'center',
  },
  artistSubtext: {
    fontSize: 14,
    color: '#999',
    marginTop: 4,
  },
  featureScreen: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  primaryButton: {
    backgroundColor: '#8420d0',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 20,
    marginBottom: 20,
    width: '100%',
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },

  // Additional Missing Session Styles
  sessionCard: {
    backgroundColor: '#8420d0',  // Temporary bright purple to test if styles are working
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  sessionCardTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  sessionCardDate: {
    color: '#999',
    fontSize: 12,
    marginTop: 2,
  },
  sessionCardInfo: {
    flex: 1,
  },
  inputGroup: {
    marginBottom: 20,
    width: '100%',
  },
  inputLabel: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  inputField: {
    backgroundColor: '#282828',
    borderRadius: 8,
    padding: 12,
    color: '#FFFFFF',
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#404040',
  },
  artistInfoCard: {
    flexDirection: 'row',
    backgroundColor: '#282828',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    alignItems: 'center',
    width: '100%',
  },
  artistImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 12,
  },
  artistInfoText: {
    flex: 1,
  },
  artistName: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  searchContainer2: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#282828',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#404040',
  },
  searchIconButton: {
    padding: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  featureScreenContainer: {
    flex: 1,
    backgroundColor: '#121212',
  },
  featureScreenContent: {
    padding: 20,
    alignItems: 'center',
  },
});
